[package]
name = "wasmpack_webpack_example"
version = "0.0.1"
authors = ["Aleksey Krasnobaev <alekseykrasnobaev@gmail.com>"]
description = ""
repository = ""
license = ""

[lib]
crate-type = ["cdylib"]
path = "./lib.rs"

[dependencies]
wasm-bindgen = "0.2.25"
