[package]
name = "wasmpack_webpack_example"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]
path = "./lib.rs"

[dependencies]
wasm-bindgen = "0.2.25"

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Window",
]
