[package]
name = "parcel_plugin_rustwasm_example"
version = "0.0.1"
authors = ["Aleksey Krasnobaev <alekseykrasnobaev@gmail.com>"]

[lib]
crate-type = ["cdylib"]
path = "./lib.rs"

[dependencies]
wasm-bindgen = "0.2.22"
